/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUtangRouteImport } from './routes/_app.utang'
import { Route as AppUnitUsahaRouteImport } from './routes/_app.unit-usaha'
import { Route as AppTransferRouteImport } from './routes/_app.transfer'
import { Route as AppPiutangRouteImport } from './routes/_app.piutang'
import { Route as AppPersediaanRouteImport } from './routes/_app.persediaan'
import { Route as AppLpjRouteImport } from './routes/_app.lpj'
import { Route as AppLaporanRouteImport } from './routes/_app.laporan'
import { Route as AppJenisUsahaRouteImport } from './routes/_app.jenis-usaha'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCatatKegiatanRouteImport } from './routes/_app.catat-kegiatan'
import { Route as AppBukuBesarRouteImport } from './routes/_app.buku-besar'
import { Route as AppAsetRouteImport } from './routes/_app.aset'
import { Route as AppAkunRouteImport } from './routes/_app.akun'
import { Route as AppAiAsistenRouteImport } from './routes/_app.ai-asisten'
import { Route as AppJurnalIndexRouteImport } from './routes/_app.jurnal.index'
import { Route as AppJurnalKoreksiRouteImport } from './routes/_app.jurnal.koreksi'
import { Route as AppJurnalBaruRouteImport } from './routes/_app.jurnal.baru'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUtangRoute = AppUtangRouteImport.update({
  id: '/utang',
  path: '/utang',
  getParentRoute: () => AppRoute,
} as any)
const AppUnitUsahaRoute = AppUnitUsahaRouteImport.update({
  id: '/unit-usaha',
  path: '/unit-usaha',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferRoute = AppTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppPiutangRoute = AppPiutangRouteImport.update({
  id: '/piutang',
  path: '/piutang',
  getParentRoute: () => AppRoute,
} as any)
const AppPersediaanRoute = AppPersediaanRouteImport.update({
  id: '/persediaan',
  path: '/persediaan',
  getParentRoute: () => AppRoute,
} as any)
const AppLpjRoute = AppLpjRouteImport.update({
  id: '/lpj',
  path: '/lpj',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanRoute = AppLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppRoute,
} as any)
const AppJenisUsahaRoute = AppJenisUsahaRouteImport.update({
  id: '/jenis-usaha',
  path: '/jenis-usaha',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCatatKegiatanRoute = AppCatatKegiatanRouteImport.update({
  id: '/catat-kegiatan',
  path: '/catat-kegiatan',
  getParentRoute: () => AppRoute,
} as any)
const AppBukuBesarRoute = AppBukuBesarRouteImport.update({
  id: '/buku-besar',
  path: '/buku-besar',
  getParentRoute: () => AppRoute,
} as any)
const AppAsetRoute = AppAsetRouteImport.update({
  id: '/aset',
  path: '/aset',
  getParentRoute: () => AppRoute,
} as any)
const AppAkunRoute = AppAkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAsistenRoute = AppAiAsistenRouteImport.update({
  id: '/ai-asisten',
  path: '/ai-asisten',
  getParentRoute: () => AppRoute,
} as any)
const AppJurnalIndexRoute = AppJurnalIndexRouteImport.update({
  id: '/jurnal/',
  path: '/jurnal/',
  getParentRoute: () => AppRoute,
} as any)
const AppJurnalKoreksiRoute = AppJurnalKoreksiRouteImport.update({
  id: '/jurnal/koreksi',
  path: '/jurnal/koreksi',
  getParentRoute: () => AppRoute,
} as any)
const AppJurnalBaruRoute = AppJurnalBaruRouteImport.update({
  id: '/jurnal/baru',
  path: '/jurnal/baru',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/ai-asisten': typeof AppAiAsistenRoute
  '/akun': typeof AppAkunRoute
  '/aset': typeof AppAsetRoute
  '/buku-besar': typeof AppBukuBesarRoute
  '/catat-kegiatan': typeof AppCatatKegiatanRoute
  '/dashboard': typeof AppDashboardRoute
  '/jenis-usaha': typeof AppJenisUsahaRoute
  '/laporan': typeof AppLaporanRoute
  '/lpj': typeof AppLpjRoute
  '/persediaan': typeof AppPersediaanRoute
  '/piutang': typeof AppPiutangRoute
  '/transfer': typeof AppTransferRoute
  '/unit-usaha': typeof AppUnitUsahaRoute
  '/utang': typeof AppUtangRoute
  '/jurnal/baru': typeof AppJurnalBaruRoute
  '/jurnal/koreksi': typeof AppJurnalKoreksiRoute
  '/jurnal/': typeof AppJurnalIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ai-asisten': typeof AppAiAsistenRoute
  '/akun': typeof AppAkunRoute
  '/aset': typeof AppAsetRoute
  '/buku-besar': typeof AppBukuBesarRoute
  '/catat-kegiatan': typeof AppCatatKegiatanRoute
  '/dashboard': typeof AppDashboardRoute
  '/jenis-usaha': typeof AppJenisUsahaRoute
  '/laporan': typeof AppLaporanRoute
  '/lpj': typeof AppLpjRoute
  '/persediaan': typeof AppPersediaanRoute
  '/piutang': typeof AppPiutangRoute
  '/transfer': typeof AppTransferRoute
  '/unit-usaha': typeof AppUnitUsahaRoute
  '/utang': typeof AppUtangRoute
  '/': typeof AppIndexRoute
  '/jurnal/baru': typeof AppJurnalBaruRoute
  '/jurnal/koreksi': typeof AppJurnalKoreksiRoute
  '/jurnal': typeof AppJurnalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/ai-asisten': typeof AppAiAsistenRoute
  '/_app/akun': typeof AppAkunRoute
  '/_app/aset': typeof AppAsetRoute
  '/_app/buku-besar': typeof AppBukuBesarRoute
  '/_app/catat-kegiatan': typeof AppCatatKegiatanRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/jenis-usaha': typeof AppJenisUsahaRoute
  '/_app/laporan': typeof AppLaporanRoute
  '/_app/lpj': typeof AppLpjRoute
  '/_app/persediaan': typeof AppPersediaanRoute
  '/_app/piutang': typeof AppPiutangRoute
  '/_app/transfer': typeof AppTransferRoute
  '/_app/unit-usaha': typeof AppUnitUsahaRoute
  '/_app/utang': typeof AppUtangRoute
  '/_app/': typeof AppIndexRoute
  '/_app/jurnal/baru': typeof AppJurnalBaruRoute
  '/_app/jurnal/koreksi': typeof AppJurnalKoreksiRoute
  '/_app/jurnal/': typeof AppJurnalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-asisten'
    | '/akun'
    | '/aset'
    | '/buku-besar'
    | '/catat-kegiatan'
    | '/dashboard'
    | '/jenis-usaha'
    | '/laporan'
    | '/lpj'
    | '/persediaan'
    | '/piutang'
    | '/transfer'
    | '/unit-usaha'
    | '/utang'
    | '/jurnal/baru'
    | '/jurnal/koreksi'
    | '/jurnal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ai-asisten'
    | '/akun'
    | '/aset'
    | '/buku-besar'
    | '/catat-kegiatan'
    | '/dashboard'
    | '/jenis-usaha'
    | '/laporan'
    | '/lpj'
    | '/persediaan'
    | '/piutang'
    | '/transfer'
    | '/unit-usaha'
    | '/utang'
    | '/'
    | '/jurnal/baru'
    | '/jurnal/koreksi'
    | '/jurnal'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/ai-asisten'
    | '/_app/akun'
    | '/_app/aset'
    | '/_app/buku-besar'
    | '/_app/catat-kegiatan'
    | '/_app/dashboard'
    | '/_app/jenis-usaha'
    | '/_app/laporan'
    | '/_app/lpj'
    | '/_app/persediaan'
    | '/_app/piutang'
    | '/_app/transfer'
    | '/_app/unit-usaha'
    | '/_app/utang'
    | '/_app/'
    | '/_app/jurnal/baru'
    | '/_app/jurnal/koreksi'
    | '/_app/jurnal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/utang': {
      id: '/_app/utang'
      path: '/utang'
      fullPath: '/utang'
      preLoaderRoute: typeof AppUtangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/unit-usaha': {
      id: '/_app/unit-usaha'
      path: '/unit-usaha'
      fullPath: '/unit-usaha'
      preLoaderRoute: typeof AppUnitUsahaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfer': {
      id: '/_app/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof AppTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/piutang': {
      id: '/_app/piutang'
      path: '/piutang'
      fullPath: '/piutang'
      preLoaderRoute: typeof AppPiutangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/persediaan': {
      id: '/_app/persediaan'
      path: '/persediaan'
      fullPath: '/persediaan'
      preLoaderRoute: typeof AppPersediaanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lpj': {
      id: '/_app/lpj'
      path: '/lpj'
      fullPath: '/lpj'
      preLoaderRoute: typeof AppLpjRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan': {
      id: '/_app/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AppLaporanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jenis-usaha': {
      id: '/_app/jenis-usaha'
      path: '/jenis-usaha'
      fullPath: '/jenis-usaha'
      preLoaderRoute: typeof AppJenisUsahaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catat-kegiatan': {
      id: '/_app/catat-kegiatan'
      path: '/catat-kegiatan'
      fullPath: '/catat-kegiatan'
      preLoaderRoute: typeof AppCatatKegiatanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buku-besar': {
      id: '/_app/buku-besar'
      path: '/buku-besar'
      fullPath: '/buku-besar'
      preLoaderRoute: typeof AppBukuBesarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aset': {
      id: '/_app/aset'
      path: '/aset'
      fullPath: '/aset'
      preLoaderRoute: typeof AppAsetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/akun': {
      id: '/_app/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AppAkunRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-asisten': {
      id: '/_app/ai-asisten'
      path: '/ai-asisten'
      fullPath: '/ai-asisten'
      preLoaderRoute: typeof AppAiAsistenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jurnal/': {
      id: '/_app/jurnal/'
      path: '/jurnal'
      fullPath: '/jurnal/'
      preLoaderRoute: typeof AppJurnalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jurnal/koreksi': {
      id: '/_app/jurnal/koreksi'
      path: '/jurnal/koreksi'
      fullPath: '/jurnal/koreksi'
      preLoaderRoute: typeof AppJurnalKoreksiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jurnal/baru': {
      id: '/_app/jurnal/baru'
      path: '/jurnal/baru'
      fullPath: '/jurnal/baru'
      preLoaderRoute: typeof AppJurnalBaruRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiAsistenRoute: typeof AppAiAsistenRoute
  AppAkunRoute: typeof AppAkunRoute
  AppAsetRoute: typeof AppAsetRoute
  AppBukuBesarRoute: typeof AppBukuBesarRoute
  AppCatatKegiatanRoute: typeof AppCatatKegiatanRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppJenisUsahaRoute: typeof AppJenisUsahaRoute
  AppLaporanRoute: typeof AppLaporanRoute
  AppLpjRoute: typeof AppLpjRoute
  AppPersediaanRoute: typeof AppPersediaanRoute
  AppPiutangRoute: typeof AppPiutangRoute
  AppTransferRoute: typeof AppTransferRoute
  AppUnitUsahaRoute: typeof AppUnitUsahaRoute
  AppUtangRoute: typeof AppUtangRoute
  AppIndexRoute: typeof AppIndexRoute
  AppJurnalBaruRoute: typeof AppJurnalBaruRoute
  AppJurnalKoreksiRoute: typeof AppJurnalKoreksiRoute
  AppJurnalIndexRoute: typeof AppJurnalIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAsistenRoute: AppAiAsistenRoute,
  AppAkunRoute: AppAkunRoute,
  AppAsetRoute: AppAsetRoute,
  AppBukuBesarRoute: AppBukuBesarRoute,
  AppCatatKegiatanRoute: AppCatatKegiatanRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppJenisUsahaRoute: AppJenisUsahaRoute,
  AppLaporanRoute: AppLaporanRoute,
  AppLpjRoute: AppLpjRoute,
  AppPersediaanRoute: AppPersediaanRoute,
  AppPiutangRoute: AppPiutangRoute,
  AppTransferRoute: AppTransferRoute,
  AppUnitUsahaRoute: AppUnitUsahaRoute,
  AppUtangRoute: AppUtangRoute,
  AppIndexRoute: AppIndexRoute,
  AppJurnalBaruRoute: AppJurnalBaruRoute,
  AppJurnalKoreksiRoute: AppJurnalKoreksiRoute,
  AppJurnalIndexRoute: AppJurnalIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
