-- Seed full BUM Desa COA per Kepmendesa 136/2022
BEGIN;
INSERT INTO public.accounts (kode_akun,nama_akun,tipe_akun,normal_balance,level,is_header,is_system_account,is_manual_input) VALUES
('1.0.00.00','ASET','ASET'::account_type,'DEBIT'::normal_balance,1,true,false,true),
('1.1.00.00','Aset Lancar','ASET'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('1.1.01.00','Kas','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.1.01.01','Kas Tunai','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.01.02','Kas di Bank BSI','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.01.03','Kas di Bank Mandiri','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.01.04','Kas di Bank BRI','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.01.05','Kas di Bank BPD','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.01.98','Kas Kecil (Petty Cash)','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.02.00','Setara Kas','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.1.02.01','Deposito <= 3 bulan','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.02.99','Setara Kas Lainnya','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.03.00','Piutang','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.1.03.01','Piutang Usaha','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.03.02','Piutang kepada Pegawai','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.03.99','Piutang Lainnya','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.04.00','Penyisihan Piutang','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.1.04.01','Penyisihan Piutang Usaha Tak Tertagih','ASET'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('1.1.04.02','Penyisihan Piutang kepada Pegawai Tak Tertagih','ASET'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('1.1.04.99','Penyisihan Piutang Lainnya Tak Tertagih','ASET'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('1.1.05.00','Persediaan','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.1.05.01','Persediaan Barang Dagangan','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.05.02','Persediaan Bahan Baku','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.05.03','Persediaan Barang Dalam Proses','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.05.04','Persediaan Barang Jadi','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.06.00','Perlengkapan','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.1.06.01','Alat Tulis Kantor (ATK)','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.07.00','Pembayaran Dimuka','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.1.07.01','Sewa Dibayar Dimuka','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.07.02','Asuransi Dibayar Dimuka','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.07.03','PPh 25','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.07.04','PPN Masukan','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.98.00','Aset Lancar Lainnya','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.1.98.99','Aset Lancar Lainnya','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.1.99.00','RK Unit Usaha','ASET'::account_type,'DEBIT'::normal_balance,3,true,true,false),
('1.1.99.01','RK Unit Wisata','ASET'::account_type,'DEBIT'::normal_balance,4,false,true,false),
('1.1.99.02','RK Unit Restoran','ASET'::account_type,'DEBIT'::normal_balance,4,false,true,false),
('1.1.99.03','RK Unit Minimart Desa','ASET'::account_type,'DEBIT'::normal_balance,4,false,true,false),
('1.1.99.04','RK Unit Gedung Serbaguna','ASET'::account_type,'DEBIT'::normal_balance,4,false,true,false),
('1.1.99.05','RK Unit Simpan Pinjam','ASET'::account_type,'DEBIT'::normal_balance,4,false,true,false),
('1.1.99.06','RK Unit Pengelolaan Air Bersih','ASET'::account_type,'DEBIT'::normal_balance,4,false,true,false),
('1.1.99.07','RK Unit Pengelolaan Sampah','ASET'::account_type,'DEBIT'::normal_balance,4,false,true,false),
('1.2.00.00','Investasi','ASET'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('1.2.01.00','Investasi','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.2.01.01','Deposito > 3 bulan','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.2.01.99','Investasi Lainnya','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.3.00.00','Aset Tetap','ASET'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('1.3.01.00','Tanah','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.3.01.01','Tanah','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.3.02.00','Kendaraan','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.3.02.01','Kendaraan','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.3.03.00','Peralatan dan Mesin','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.3.03.01','Peralatan dan Mesin','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.3.04.00','Meubelair','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.3.04.01','Meubelair','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.3.05.00','Gedung dan Bangunan','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.3.05.01','Gedung dan Bangunan','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.3.06.00','Konstruksi Dalam Pengerjaan','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.3.06.01','Konstruksi Dalam Pengerjaan','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.3.07.00','Akumulasi Penyusutan Aset Tetap','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.3.07.01','Akumulasi Penyusutan Kendaraan','ASET'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('1.3.07.02','Akumulasi Penyusutan Peralatan dan Mesin','ASET'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('1.3.07.03','Akumulasi Penyusutan Meubelair','ASET'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('1.3.07.04','Akumulasi Penyusutan Gedung dan Bangunan','ASET'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('1.3.99.00','Aset Tetap Lainnya','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.3.99.99','Aset Tetap Lainnya','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.4.00.00','Aset Takberwujud','ASET'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('1.4.01.00','Aset Takberwujud','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.4.01.01','Software','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.4.01.02','Patent','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.4.01.03','Trademark','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.4.02.00','Amortisasi Aset Takberwujud','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.4.02.01','Amortisasi Aset Takberwujud','ASET'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('1.9.00.00','Aset Lain-lain','ASET'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('1.9.01.00','Aset Lain-lain','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.9.01.01','Aset Lain-lain','ASET'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('1.9.02.00','Akumulasi Penyusutan Aset Lain-lain','ASET'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('1.9.02.01','Akumulasi Penyusutan Aset Lain-lain','ASET'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.0.00.00','KEWAJIBAN','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,1,true,false,true),
('2.1.00.00','Kewajiban Jangka Pendek','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,2,true,false,true),
('2.1.01.00','Utang Usaha','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('2.1.01.01','Utang Usaha','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.1.02.00','Utang Pajak','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('2.1.02.01','PPN Keluaran','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.1.02.02','PPh 21','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.1.02.03','PPh 23','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.1.02.04','PPh 29','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.1.03.00','Utang Gaji/Upah dan Tunjangan','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('2.1.03.01','Utang Gaji dan Tunjangan','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.1.03.02','Utang Gaji/Upah Karyawan','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.1.04.00','Utang Utilitas','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('2.1.04.01','Utang Listrik','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.1.04.02','Utang Telepon/Internet','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.1.04.99','Utang Utilitas Lainnya','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.1.05.00','Utang kepada Pihak Ketiga Jk. Pendek','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('2.1.05.01','Utang kepada Pihak Ketiga Jk. Pendek','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.1.05.99','Utang kepada Pihak Ketiga Jk. Pendek Lainnya','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.1.99.00','Utang Jangka Pendek Lainnya','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('2.1.99.99','Utang Jangka Pendek Lainnya','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.2.00.00','Kewajiban Jangka Panjang','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,2,true,false,true),
('2.2.01.00','Utang Ke Bank','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('2.2.01.01','Utang Ke Bank','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.2.02.00','Utang kepada Pihak Ketiga Jk. Panjang','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('2.2.02.01','Utang kepada Pihak Ketiga Jk. Panjang','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('2.2.99.00','Utang Jangka Panjang Lainnya','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('2.2.99.99','Utang Jangka Panjang Lainnya','KEWAJIBAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('3.0.00.00','EKUITAS','EKUITAS'::account_type,'KREDIT'::normal_balance,1,true,false,true),
('3.1.00.00','Modal Pemilik','EKUITAS'::account_type,'KREDIT'::normal_balance,2,true,false,true),
('3.1.01.00','Penyertaan Modal Desa','EKUITAS'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('3.1.01.01','Penyertaan Modal Desa','EKUITAS'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('3.1.02.00','Penyertaan Modal Masyarakat','EKUITAS'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('3.1.02.01','Penyertaan Modal Masyarakat A','EKUITAS'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('3.1.02.02','Penyertaan Modal Masyarakat B','EKUITAS'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('3.1.02.03','Penyertaan Modal Masyarakat C','EKUITAS'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('3.1.02.04','Penyertaan Modal Masyarakat D','EKUITAS'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('3.2.00.00','Pengambilan oleh Pemilik','EKUITAS'::account_type,'KREDIT'::normal_balance,2,true,false,true),
('3.2.01.00','Bagi Hasil Penyertaan Modal Desa','EKUITAS'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('3.2.01.01','Bagi Hasil Penyertaan Modal Desa','EKUITAS'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('3.2.01.02','Bagi Hasil Penyertaan Modal Desa A','EKUITAS'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('3.2.01.03','Bagi Hasil Penyertaan Modal Desa B','EKUITAS'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('3.2.01.04','Bagi Hasil Penyertaan Modal Desa C','EKUITAS'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('3.2.02.00','Bagi Hasil Penyertaan Modal Masyarakat','EKUITAS'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('3.2.02.01','Bagi Hasil Penyertaan Modal Masyarakat','EKUITAS'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('3.2.02.02','Bagi Hasil Penyertaan Modal Masyarakat Desa A','EKUITAS'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('3.2.02.03','Bagi Hasil Penyertaan Modal Masyarakat Desa B','EKUITAS'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('3.2.02.04','Bagi Hasil Penyertaan Modal Masyarakat Desa C','EKUITAS'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('3.3.00.00','Saldo Laba','EKUITAS'::account_type,'KREDIT'::normal_balance,2,true,false,true),
('3.3.01.00','Saldo Laba','EKUITAS'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('3.3.01.01','Saldo Laba Tidak Dicadangkan','EKUITAS'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('3.3.01.02','Saldo Laba Dicadangkan untuk Pembelian Aset Tetap','EKUITAS'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('3.3.01.03','Saldo Laba Dicadangkan untuk Pembayaran Utang Jangka Panjang','EKUITAS'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('3.4.00.00','Modal Donasi/Sumbangan','EKUITAS'::account_type,'KREDIT'::normal_balance,2,true,false,true),
('3.4.01.00','Modal Donasi/Sumbangan','EKUITAS'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('3.4.01.01','Modal Donasi/Sumbangan','EKUITAS'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('3.8.00.00','RK Pusat','EKUITAS'::account_type,'KREDIT'::normal_balance,2,true,true,false),
('3.8.01.00','RK Pusat','EKUITAS'::account_type,'KREDIT'::normal_balance,3,true,true,false),
('3.8.01.01','RK Pusat','EKUITAS'::account_type,'DEBIT'::normal_balance,4,false,true,false),
('3.9.00.00','Ikhtisar Laba Rugi','EKUITAS'::account_type,'KREDIT'::normal_balance,2,true,false,true),
('3.9.01.00','Ikhtisar Laba Rugi','EKUITAS'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('3.9.01.01','Ikhtisar Laba Rugi','EKUITAS'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.0.00.00','PENDAPATAN USAHA','PENDAPATAN'::account_type,'KREDIT'::normal_balance,1,true,false,true),
('4.1.00.00','Pendapatan Jasa','PENDAPATAN'::account_type,'KREDIT'::normal_balance,2,true,false,true),
('4.1.01.00','Pendapatan Wisata','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.1.01.01','Pendapatan Tiket','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.01.02','Pendapatan Wahana','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.01.03','Pendapatan Paket Wisata','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.02.00','Pendapatan Pengelolaan Air Bersih','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.1.02.01','Pendapatan Pengelolaan Air Bersih','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.03.00','Pendapatan Pengelolaan Sampah','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.1.03.01','Pendapatan Pengelolaan Sampah','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.04.00','Pendapatan Sewa','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.1.04.01','Pendapatan Sewa Tempat Outbound','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.04.02','Pendapatan Sewa Tempat untuk Toko/Kios','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.04.03','Pendapatan Sewa Gedung','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.04.04','Pendapatan Sewa Mobil','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.04.05','Pendapatan Sewa Peralatan Gedung','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.04.99','Pendapatan Sewa Lainnya','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.05.00','Pendapatan Jasa Pelayanan','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.1.05.01','Pendapatan Jasa Pembayaran Listrik','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.05.99','Pendapatan Jasa Pelayanan Lainnya','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.06.00','Pendapatan Transportasi','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.1.06.01','Pendapatan Transportasi','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.07.00','Pendapatan Parkir','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.1.07.01','Pendapatan Parkir Mobil','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.07.02','Pendapatan Parkir Motor','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.08.00','Pendapatan Simpan Pinjam','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.1.08.01','Pendapatan Simpan Pinjam','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.09.00','Pendapatan Pelatihan','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.1.09.01','Pendapatan Pelatihan','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.10.00','Pendapatan Penginapan/Homestay','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.1.10.01','Pendapatan Homestay','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.1.11.00','Pendapatan Komisi','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.1.11.01','Pendapatan Komisi','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.2.00.00','Pendapatan Penjualan Barang Dagangan','PENDAPATAN'::account_type,'KREDIT'::normal_balance,2,true,false,true),
('4.2.01.00','Pendapatan Penjualan Barang Dagangan','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.2.01.01','Pendapatan Penjualan Makanan/Minuman','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.2.01.02','Pendapatan Penjualan Pakaian/Kaos/Jaket','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.2.01.03','Pendapatan Penjualan Hasil Kerajinan/Suvenir','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.2.01.04','Pendapatan Penjualan Buku','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.2.01.05','Pendapatan Penjualan Biji Kopi','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.2.01.06','Pendapatan Penjualan Bensin','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.2.01.99','Diskon Penjualan Barang Dagangan','PENDAPATAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('4.3.00.00','Pendapatan Penjualan Barang Jadi','PENDAPATAN'::account_type,'KREDIT'::normal_balance,2,true,false,true),
('4.3.01.00','Pendapatan Penjualan Barang Jadi','PENDAPATAN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('4.3.01.01','Pendapatan Katering','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.3.01.02','Pendapatan Restoran','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.3.01.03','Pendapatan Kopi','PENDAPATAN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('4.3.01.04','Diskon Penjualan Barang Jadi','PENDAPATAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('5.0.00.00','HARGA POKOK PRODUKSI DAN PENJUALAN','HPP'::account_type,'DEBIT'::normal_balance,1,true,false,true),
('5.1.00.00','Harga Pokok Penjualan Barang Dagangan','HPP'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('5.1.01.00','Harga Pokok Penjualan Barang Dagangan','HPP'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('5.1.01.01','Harga Pokok Penjualan Barang Dagangan','HPP'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('5.2.00.00','Harga Pokok Penjualan Barang Jadi','HPP'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('5.2.01.00','Harga Pokok Penjualan Barang Jadi','HPP'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('5.2.01.01','Harga Pokok Penjualan Barang Jadi','HPP'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('5.3.00.00','Harga Pokok Produksi','HPP'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('5.3.01.00','Harga Pokok Produksi','HPP'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('5.3.01.01','Harga Pokok Produksi','HPP'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.0.00.00','BEBAN-BEBAN USAHA','BEBAN'::account_type,'DEBIT'::normal_balance,1,true,false,true),
('6.1.00.00','Beban Administrasi dan Umum','BEBAN'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('6.1.01.00','Beban Pegawai Bagian Administrasi Umum','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.1.01.01','Beban Gaji dan Tunjangan Bag. Adum','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.01.02','Beban Honor Lembur Bag. Adum','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.01.03','Beban Honor Narasumber','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.01.04','Beban Insentif (Bonus) Bag. Adum','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.01.05','Beban Komisi Bag. Adum','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.01.06','Beban Seragam Pegawai Bag. Adum','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.01.07','Beban Penguatan SDM','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.01.99','Beban Pegawai Bag. Adum Lainnya','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.02.00','Beban Perlengkapan','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.1.02.01','Beban Alat Tulis Kantor (ATK)','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.02.02','Beban Foto Copy','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.02.03','Beban Konsumsi Rapat','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.02.04','Beban Cetak dan Dekorasi','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.02.99','Beban Perlengkapan Lainnya','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.03.00','Beban Pemeliharaan dan Perbaikan','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.1.03.01','Beban Pemeliharaan dan Perbaikan','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.04.00','Beban Utilitas','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.1.04.01','Beban Listrik','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.04.02','Beban Telepon/Internet','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.04.99','Beban Utilitas Lainnya','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.05.00','Beban Sewa dan Asuransi','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.1.05.01','Beban Sewa','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.05.02','Beban Asuransi','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.06.00','Beban Kebersihan dan Keamanan','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.1.06.01','Beban Kebersihan','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.06.02','Beban Keamanan','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.07.00','Beban Penyisihan dan Penyusutan/Amortisasi','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.1.07.01','Beban Penyisihan Piutang Tak Tertagih','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.07.02','Beban Penyusutan Kendaraan','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.07.03','Beban Penyusutan Peralatan dan Mesin','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.07.04','Beban Penyusutan Meubelair','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.07.05','Beban Penyusutan Gedung dan Bangunan','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.07.06','Beban Amortisasi Aset Takberwujud','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.99.00','Beban Administrasi dan Umum Lainnya','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.1.99.01','Beban Parkir','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.99.02','Beban Audit','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.99.03','Beban Perjalanan Dinas','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.99.04','Beban Transportasi','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.99.05','Beban Jamuan Tamu','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.1.99.99','Beban Administrasi dan Umum Lainnya','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.2.00.00','Beban Operasional','BEBAN'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('6.2.01.00','Beban Pegawai Bagian Operasional','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.2.01.01','Beban Gaji/Upah Bag. Operasional','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.2.01.02','Beban Uang Makan Bag. Operasional','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.2.02.00','Beban Pemeliharaan dan Perbaikan','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.2.02.01','Beban Pemeliharaan Wahana','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.2.02.02','Beban Perbaikan dan Renovasi','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.2.03.00','Beban Keamanan','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.2.03.01','Beban Tim SAR','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.2.03.02','Beban P3K','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.2.99.00','Beban Operasional Lainnya','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.2.99.01','Beban Komunikasi','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.2.99.02','Beban Sewa Lokasi','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.2.99.03','Beban Pakan Ikan','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.2.99.99','Beban Operasional Lainnya','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.3.00.00','Beban Pemasaran','BEBAN'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('6.3.01.00','Beban Pegawai Bagian Pemasaran','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.3.01.01','Beban Gaji/Upah Bag. Pemasaran','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.3.01.02','Beban Insentif (Bonus) Bag. Pemasaran','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.3.01.03','Beban Seragam Pegawai Bag. Pemasaran','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.3.02.00','Beban Iklan dan Promosi','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.3.02.01','Beban Iklan','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.3.02.02','Beban Promosi Wartawan','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.3.02.03','Beban Dana Sosial','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('6.3.99.00','Beban Pemasaran Lainnya','BEBAN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('6.3.99.99','Beban Pemasaran Lainnya','BEBAN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.0.00.00','PENDAPATAN DAN BEBAN LAIN-LAIN','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,1,true,false,true),
('7.1.00.00','Pendapatan Lain-lain','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,2,true,false,true),
('7.1.01.00','Pendapatan dari Bank','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('7.1.01.01','Pendapatan Bunga Bank','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('7.1.01.02','Pendapatan Fee Agen BNI 46','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('7.1.02.00','Pendapatan Dividen','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('7.1.02.01','Pendapatan Dividen','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('7.1.03.00','Pendapatan Denda','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('7.1.03.01','Pendapatan Denda','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('7.1.04.00','Pendapatan Iklan','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('7.1.04.01','Pendapatan Iklan','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('7.1.05.00','Pendapatan Penjualan Aset Tetap','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('7.1.05.01','Keuntungan Penjualan Aset Tetap','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('7.1.99.00','Pendapatan Lain-lain Lainnya','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,3,true,false,true),
('7.1.99.99','Pendapatan Lain-lain Lainnya','PENDAPATAN_LAIN'::account_type,'KREDIT'::normal_balance,4,false,false,true),
('7.2.00.00','Beban Lain-lain','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('7.2.01.00','Beban Bank','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('7.2.01.01','Beban Administrasi Bank','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.2.02.00','Beban Bunga','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('7.2.02.01','Beban Bunga','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.2.03.00','Beban Denda','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('7.2.03.01','Beban Denda','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.2.04.00','Beban Penjualan Aset Tetap','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('7.2.04.01','Kerugian Penjualan Aset Tetap','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.2.99.00','Beban Lain-lain Lainnya','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('7.2.99.99','Beban Lain-lain Lainnya','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.3.00.00','Beban Pajak','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,2,true,false,true),
('7.3.01.00','Beban Pajak','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,3,true,false,true),
('7.3.01.01','Beban Pajak Air Permukaan','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.3.01.02','Beban Pajak Bunga Bank','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.3.01.03','Beban Pajak Daerah','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.3.01.04','Beban Pajak Hiburan','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.3.01.05','Beban Pajak Reklame','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.3.01.06','Beban PPh 21','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.3.01.07','Beban PPh 23','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.3.01.08','Beban PPh 25','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.3.01.09','Beban PPh 29','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.3.01.10','Beban PPh Final','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true),
('7.3.01.99','Beban Pajak Lainnya','BEBAN_LAIN'::account_type,'DEBIT'::normal_balance,4,false,false,true)
ON CONFLICT (kode_akun) DO UPDATE SET nama_akun=EXCLUDED.nama_akun, tipe_akun=EXCLUDED.tipe_akun, normal_balance=EXCLUDED.normal_balance, level=EXCLUDED.level, is_header=EXCLUDED.is_header, is_system_account=EXCLUDED.is_system_account, is_manual_input=EXCLUDED.is_manual_input, is_active=true, updated_at=now();

-- Wire parent_id by computing parent kode_akun from structure
UPDATE public.accounts c SET parent_id = p.id
FROM public.accounts p
WHERE p.kode_akun = CASE
  WHEN split_part(c.kode_akun,'.',4) <> '00' THEN split_part(c.kode_akun,'.',1)||'.'||split_part(c.kode_akun,'.',2)||'.'||split_part(c.kode_akun,'.',3)||'.00'
  WHEN split_part(c.kode_akun,'.',3) <> '00' THEN split_part(c.kode_akun,'.',1)||'.'||split_part(c.kode_akun,'.',2)||'.00.00'
  WHEN split_part(c.kode_akun,'.',2) <> '0'  THEN split_part(c.kode_akun,'.',1)||'.0.00.00'
  ELSE NULL
END
AND c.kode_akun <> p.kode_akun;

UPDATE public.accounts SET parent_id = NULL WHERE level = 1;

COMMIT;